apiVersion: v1
kind: Service
metadata:
  name: fidelizamaisvoce-deployment-service
spec:
  selector:
    app: fidelizamaisvoce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
